wip

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -115,7 +115,7 @@ jobs:
           path: docs.tgz
 
   test:
-    name: "Test"
+    name: Test
     timeout-minutes: 30
     runs-on: ubuntu-latest
     needs:
@@ -159,6 +159,22 @@ jobs:
 
       - name: Test
         run: pnpm test
+
+  benchmark:
+    name: Benchmark
+    runs-on: ubuntu-latest
+    needs:
+      - build
+    steps:
+      - run: echo "skip"
+
+  e2e-test:
+    name: E2E Test
+    runs-on: ubuntu-latest
+    needs:
+      - build
+    steps:
+      - run: echo "skip"
 
   # unit-tests:
   #   name: "Unit Tests"
@@ -355,41 +371,41 @@ jobs:
   #         name: ${{ steps.diff.outputs.diff_name }}
   #         path: ${{ steps.diff.outputs.diff_name }}
 
-  # quality-gate:
-  #   name: Quality Gate
-  #   runs-on: ubuntu-latest
-  #   needs:
-  #     - build
-  #     - e2e
-  #     - benchmarks
-  #     - unit-tests
-  #   steps:
-  #     - name: Download patches
-  #       uses: actions/download-artifact@v3
-  #     - name: Check patches
-  #       run: |
-  #         PATCH_COUNT=0
-  #         for f in $(find ./*.diff/*.diff); do
-  #           PATCH_COUNT=$((PATCH_COUNT + 1))
-  #           cat $f
-  #         done
-  #         if [ $PATCH_COUNT -gt 0 ]; then
-  #           echo "Found $PATCH_COUNT patches, build failed. A self-mutation should happen soon."
-  #           exit 1
-  #         fi
-  #     - name: All good
-  #       run: echo "Builds and tests passed! 🎉🎉🎉"
+  quality-gate:
+    name: Quality Gate
+    runs-on: ubuntu-latest
+    needs:
+      - build
+      - e2e-test
+      - benchmark
+      - test
+    steps:
+      - name: Download patches
+        uses: actions/download-artifact@v3
+      - name: Check patches
+        run: |
+          PATCH_COUNT=0
+          for f in $(find ./*.diff/*.diff); do
+            PATCH_COUNT=$((PATCH_COUNT + 1))
+            cat $f
+          done
+          if [ $PATCH_COUNT -gt 0 ]; then
+            echo "Found $PATCH_COUNT patches, build failed. A self-mutation should happen soon."
+            exit 1
+          fi
+      - name: All good
+        run: echo "Builds and tests passed! 🎉🎉🎉"
 
-  # publish:
-  #   name: Publish
-  #   if: ${{ github.event_name == 'push' && github.repository == 'winglang/wing' && github.ref == 'refs/heads/main' }}
-  #   needs:
-  #     - quality-gate
-  #     - build
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Download Build Artifacts
-  #       uses: actions/download-artifact@v3
+  publish:
+    name: Publish
+    if: ${{ github.event_name == 'push' && github.repository == 'winglang/wing' && github.ref == 'refs/heads/main' }}
+    needs:
+      - quality-gate
+      - build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download Build Artifacts
+        uses: actions/download-artifact@v3
 
   #     - name: Tag commit
   #       uses: tvdias/github-tagger@v0.0.1
